spring:
  # 데이터베이스 연결 설정
  datasource: # 여러 DBaaS에서 가져오기
    url: jdbc:mysql://mysql-346fa04d-rhdudqls73-391f.k.aivencloud.com:12507/defaultdb
    username: avnadmin
    password: AVNS_qTvkdsLx4SualZU5wuo
    driver-class-name: com.mysql.cj.jdbc.Driver